### ISSUE TITLE
Could not find package j-arnaiz/behat-junit-formatter at any version for your minimum-stability (stable). 

### ISSUE THREAD

**Issue by narozhniyy** [j-arnaiz/behat-junit-formatter#1]
Need help! Can't install this package with composer.

behat$ composer require --dev j-arnaiz/behat-junit-formatter

  [InvalidArgumentException]  
  Could not find package j-arnaiz/behat-junit-formatter at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability

**Comment by narozhniyy** [comment]
Guys please be careful when you write docs or tutorials, on your github page with this package you wrote:

$ composer require --dev j-arnaiz/behat-junit-formatter

And I have error described above. Please change this line in your docs on :

$ composer require --dev jarnaiz/behat-junit-formatter

And this will work, thanks

**Comment by j-arnaiz** [comment]
Thanks, my fault.
