### ISSUE TITLE
Documentation seems imcomplete

### ISSUE THREAD

**Issue by garyrutland** [j-arnaiz/behat-junit-formatter#11]
Hi,

Recently had the issue that JUnit isn't supported by Behat 3.0 and came across this repo.
It looks like you might be missing a line or an explanation to the full set up.
It doesn't mention anywhere that you still need to include the "-f junit" or "--format junit" to either the command line or to the YML file.

This might just be me being a bit dense, but it wasn't obvious to me that it still needed to be done.

Thanks,
Gary

**Comment by j-arnaiz** [comment]
Ok, thank you Gary.

I add this in README.md
