### ISSUE TITLE
Formatter not found or registered

### ISSUE THREAD

**Issue by adam-paterson** [j-arnaiz/behat-junit-formatter#13]
Hey @j-arnaiz,

First of all, thanks for this package bridging the gap between Behat 2.x and 3.x.

Running locally with the formatter installed it runs perfectly and generates the junit.xml as expected. However on our CI server we're getting the following:

```
`junit` formatter is not found or has not been properly registered. Registered formatters: `progress`, `pretty`.
```

Obviously not an issue with this package, just wondered if you had seen it before or have any idea how we can resolve this.

**Comment by j-arnaiz** [comment]
Sorry I can't help you, but behat 3.1 now supports junit

**Comment by j-arnaiz** [comment]
I close the issue, if you think is a problem with this package please open a new one with details of your ci configuration.
