### ISSUE TITLE
Ampersand in failed test message causing PHP Warning due to XML entity

### ISSUE THREAD

**Issue by konrness** [j-arnaiz/behat-junit-formatter#14]
When a test result exception message includes an ampersand, such as a URL with parameters, the following PHP warning will result and the test result message will not be included in JUnit XML.

```
PHP Warning:  SimpleXMLElement::addChild(): unterminated entity reference
```

Stack Trace points to:

```
SimpleXMLElement->addChild() /vendor/jarnaiz/behat-junit-formatter/src/Formatter/JUnitFormatter.php:246
```

**Comment by j-arnaiz** [comment]
Try to update to behat 3.1 it supports junit now.

**Comment by higrow** [comment]
seeing the same issue, does anything speak against merging the PR?
behat 3.1 is still an RC and does not include the optional "time" attribute quite yet. 

if you find the time to merge this it would be a great help. thanks anyway.

**Comment by konrness** [comment]
I have updated the pull request to put failure message in a CDATA node instead of using htmlentities() as I was finding issues with &nbsp; and &ndash; elements in error messages.

@j-arnaiz once Behat 3.1 is stable, will this package be deprecated?
