### ISSUE TITLE
Logged only last suite

### ISSUE THREAD

**Issue by extdevelopment** [j-arnaiz/behat-junit-formatter#3]
If in behat.yml defined more than one suite, behat-junit-formatter logged only last one.
Thx for your help

**Comment by j-arnaiz** [comment]
hello,

Could you send me your behat.yml to check it.

Thank you!.

**Comment by extdevelopment** [comment]
@j-arnaiz my behat.yml 
thx

<pre>
imports:
    - behat.jenkins.yml
    # https://behat.readthedocs.org/en/v2.5/guides/7.config.html#imports
default:
  extensions:
    Behat\Symfony2Extension: ~
    # https://github.com/PolishSymfonyCommunity/Symfony2MockerExtension/issues/5#issuecomment-36241378
    # not work with behat 3:(
    # PSS\Behat\Symfony2MockerExtension\Extension: ~
    Rezzza\MockExtension\Extension: ~
    Behat\MinkExtension:
      base_url: 'http://localhost/symfony/jobexam1/web/app_dev.php'
      sessions:
        symfony2:
          symfony2: ~
#          selenium2: ~
        javascript:
          selenium2: ~
      browser_name: chrome
      show_auto: false
      show_cmd: firefox %s
    jarnaiz\JUnitFormatter\JUnitFormatterExtension:
        filename: behat-junit-report.xml
        outputDir: "%paths.base%/app/build/reports"
  suites:
    weather_suite:
      type: symfony_bundle
      bundle: 'ExtdevelopmentWeatherBundle'
      contexts:
        - Behat\MinkExtension\Context\MinkContext
        - Extdevelopment\WeatherBundle\Features\Context\FeatureContext
    shop_suite:
      type: symfony_bundle
      bundle: 'ExtdevelopmentJobExamBundle'
      contexts:
        - Behat\MinkExtension\Context\MinkContext
        - Extdevelopment\JobExamBundle\Features\Context\FeatureContext
</pre>

**Comment by Merenptah** [comment]
I'm having the same issue. The problem is that the code can't work with several suites. The document is written with each afterSuite hook, hence only the last suite will remain. But I also do not see a quick way around, since the JUnitFormatter is based only on the behat hooks, and there are no behat hooks for "beforeAllSuites" and "afterAllSuites", or am I mistaken?

**Comment by extdevelopment** [comment]
@j-arnaiz 
I update j-arnaiz/behat-junit-formatter to v1.1.1.
Not change my behat.yml, and it is not at all made ​​log file.
thx

**Comment by extdevelopment** [comment]
v1.1.1. works fine for me!
THX
