### ISSUE TITLE
default testsuite without tests attribute added

### ISSUE THREAD

**Issue by phiamo** [j-arnaiz/behat-junit-formatter#7]
Hi, 
when using this jenkins complains sometimes about a not valid xml:

xmllint --noout --schema junit-4.xsd app/build/behat/report.xml 
app/build/behat/report.xml:3: element testsuite: Schemas validity error : Element 'testsuite': The attribute 'tests' is required but missing.
app/build/behat/report.xml fails to validate

the following is generated as first suite:
  <testsuite name="default"/>

cheers phil

**Comment by mvhirsch** [comment]
I got the same problem. It currently prevents me from using behat within jenkins effectively.

```
build/tests/features.xml:3: element testsuite: Schemas validity error : Element 'testsuite': The attribute 'tests' is required but missing.
build/tests/features.xml:13: element testsuite: Schemas validity error : Element 'testsuite': The attribute 'tests' is required but missing.
build/tests/features.xml fails to validate
```

In my behat.yml I have:

```
jarnaiz\JUnitFormatter\JUnitFormatterExtension:
    filename: features.xml
```

EDIT: In version 1.1.0 I can't reproduce the problem anymore. But since I'm using multiple suites, I'm fetching the problem solved in #3.

**Comment by phiamo** [comment]
latest behat branch has this feature in it too, if you need a fast solution

**Comment by mvhirsch** [comment]
@phiamo Thank you!

**Comment by j-arnaiz** [comment]
I closed then, if any problem please open a new issue.

Thank you all.
